export const ingredientsList = [
    { value: "turmeric", label: "Turmeric" },
    { value: "cumin", label: "Cumin" },
    { value: "coriander", label: "Coriander" },
    { value: "mustard_seeds", label: "Mustard Seeds" },
    { value: "ginger", label: "Ginger" },
    { value: "garlic", label: "Garlic" },
    { value: "green_chilies", label: "Green Chilies" },
    { value: "onions", label: "Onions" },
    { value: "tomatoes", label: "Tomatoes" },
    { value: "sugar", label: "Sugar" },
    { value: "salt", label: "Salt" },
    { value: "curry_leaves", label: "Curry Leaves" },
    { value: "red_chili_powder", label: "Red Chili Powder" },
    { value: "garam_masala", label: "Garam Masala" },
    { value: "fenugreek_leaves", label: "Fenugreek Leaves" },
    { value: "cloves", label: "Cloves" },
    { value: "cardamom", label: "Cardamom" },
    { value: "cinnamon", label: "Cinnamon" },
    { value: "bay_leaves", label: "Bay Leaves" },
    { value: "black_pepper", label: "Black Pepper" },
    { value: "white_pepper", label: "White Pepper" },
    { value: "paprika", label: "Paprika" },
    { value: "nutmeg", label: "Nutmeg" },
    { value: "mace", label: "Mace" },
    { value: "star_anise", label: "Star Anise" },
    { value: "sumac", label: "Sumac" },
    { value: "saffron", label: "Saffron" },
    { value: "turmeric_root", label: "Turmeric Root" },
    { value: "asafoetida", label: "Asafoetida" },
    { value: "smoked_paprika", label: "Smoked Paprika" },
    { value: "cayenne_pepper", label: "Cayenne Pepper" },
    { value: "chili_flakes", label: "Chili Flakes" },
    { value: "mint_leaves", label: "Mint Leaves" },
    { value: "basil_leaves", label: "Basil Leaves" },
    { value: "oregano", label: "Oregano" },
    { value: "thyme", label: "Thyme" },
    { value: "rosemary", label: "Rosemary" },
    { value: "parsley", label: "Parsley" },
    { value: "cilantro", label: "Cilantro" },
    { value: "dill", label: "Dill" },
    { value: "chives", label: "Chives" },
    { value: "tarragon", label: "Tarragon" },
    { value: "lemongrass", label: "Lemongrass" },
    { value: "bay_leaf", label: "Bay Leaf" },
    { value: "sage", label: "Sage" },
    { value: "fennel", label: "Fennel" },
    { value: "rice", label: "Rice" },
    { value: "quinoa", label: "Quinoa" },
    { value: "oats", label: "Oats" },
    { value: "barley", label: "Barley" },
    { value: "millet", label: "Millet" },
    { value: "couscous", label: "Couscous" },
    { value: "bulgur", label: "Bulgur" },
    { value: "farro", label: "Farro" },
    { value: "rye", label: "Rye" },
    { value: "spelt", label: "Spelt" },
    { value: "sorghum", label: "Sorghum" },
    { value: "potatoes", label: "Potatoes" },
    { value: "sweet_potatoes", label: "Sweet Potatoes" },
    { value: "carrots", label: "Carrots" },
    { value: "cauliflower", label: "Cauliflower" },
    { value: "broccoli", label: "Broccoli" },
    { value: "zucchini", label: "Zucchini" },
    { value: "eggplant", label: "Eggplant" },
    { value: "bell_peppers", label: "Bell Peppers" },
    { value: "spinach", label: "Spinach" },
    { value: "kale", label: "Kale" },
    { value: "mushrooms", label: "Mushrooms" },
    { value: "peas", label: "Peas" },
    { value: "green_beans", label: "Green Beans" },
    { value: "asparagus", label: "Asparagus" },
    { value: "artichoke", label: "Artichoke" },
    { value: "cabbage", label: "Cabbage" },
    { value: "brussels_sprouts", label: "Brussels Sprouts" },
    { value: "radishes", label: "Radishes" },
    { value: "cucumber", label: "Cucumber" },
    { value: "beets", label: "Beets" },
    { value: "lettuce", label: "Lettuce" },
    { value: "arugula", label: "Arugula" },
    { value: "lemons", label: "Lemons" },
    { value: "limes", label: "Limes" },
    { value: "oranges", label: "Oranges" },
    { value: "apples", label: "Apples" },
    { value: "bananas", label: "Bananas" },
    { value: "grapes", label: "Grapes" },
    { value: "strawberries", label: "Strawberries" },
    { value: "blueberries", label: "Blueberries" },
    { value: "pineapple", label: "Pineapple" },
    { value: "mango", label: "Mango" },
    { value: "papaya", label: "Papaya" },
    { value: "watermelon", label: "Watermelon" },
    { value: "pears", label: "Pears" },
    { value: "plums", label: "Plums" },
    { value: "kiwi", label: "Kiwi" },
    { value: "pomegranate", label: "Pomegranate" },
    { value: "milk", label: "Milk" },
    { value: "eggs", label: "Eggs" },
    { value: "chicken", label: "Chicken" },
    { value: "beef", label: "Beef" },
    { value: "pork", label: "Pork" },
    { value: "lamb", label: "Lamb" },
    { value: "goat_meat", label: "Goat Meat" },
    { value: "salmon", label: "Salmon" },
    { value: "tuna", label: "Tuna" },
    { value: "lobster", label: "Lobster" },
    { value: "shrimp", label: "Shrimp" },
    { value: "mussels", label: "Mussels" },
    { value: "yogurt", label: "Yogurt" },
    { value: "butter", label: "Butter" },
    { value: "cheese", label: "Cheese" },
    { value: "cream", label: "Cream" },
    { value: "duck", label: "Duck" },
    { value: "turkey", label: "Turkey" },
    { value: "goose", label: "Goose" },
    { value: "sheep_milk", label: "Sheep Milk" },
    { value: "goat_cheese", label: "Goat Cheese" },
    { value: "duck_eggs", label: "Duck Eggs" },
    { value: "honey", label: "Honey" },
    { value: "peanuts", label: "Peanuts" },
    { value: "almonds", label: "Almonds" },
    { value: "walnuts", label: "Walnuts" },
    { value: "cashews", label: "Cashews" },
    { value: "pistachios", label: "Pistachios" },
    { value: "sunflower_seeds", label: "Sunflower Seeds" },
    { value: "chia_seeds", label: "Chia Seeds" },
    { value: "flax_seeds", label: "Flax Seeds" },
    { value: "pumpkin_seeds", label: "Pumpkin Seeds" },
    { value: "sesame_seeds", label: "Sesame Seeds" },
    { value: "pine_nuts", label: "Pine Nuts" },
{ value: "pecans", label: "Pecans" },
{ value: "macadamia_nuts", label: "Macadamia Nuts" },
{ value: "hazelnuts", label: "Hazelnuts" },
{ value: "brazil_nuts", label: "Brazil Nuts" },
{ value: "coconut", label: "Coconut" },
{ value: "amaranth", label: "Amaranth" },
{ value: "buckwheat", label: "Buckwheat" },
{ value: "wild_rice", label: "Wild Rice" },
{ value: "teff", label: "Teff" },
{ value: "freekeh", label: "Freekeh" },
{ value: "turnips", label: "Turnips" },
{ value: "parsnips", label: "Parsnips" },
{ value: "rutabaga", label: "Rutabaga" },
{ value: "kohlrabi", label: "Kohlrabi" },
{ value: "celery_root", label: "Celery Root" },
{ value: "daikon", label: "Daikon" },
{ value: "jicama", label: "Jicama" },
{ value: "watercress", label: "Watercress" },
{ value: "endive", label: "Endive" },
{ value: "radicchio", label: "Radicchio" },
{ value: "bok_choy", label: "Bok Choy" },
{ value: "tatsoi", label: "Tatsoi" },
{ value: "napa_cabbage", label: "Napa Cabbage" },
{ value: "figs", label: "Figs" },
{ value: "dates", label: "Dates" },
{ value: "apricots", label: "Apricots" },
{ value: "peaches", label: "Peaches" },
{ value: "nectarines", label: "Nectarines" },
{ value: "cherries", label: "Cherries" },
{ value: "blackberries", label: "Blackberries" },
{ value: "raspberries", label: "Raspberries" },
{ value: "gooseberries", label: "Gooseberries" },
{ value: "cranberries", label: "Cranberries" },
{ value: "quail", label: "Quail" },
{ value: "pheasant", label: "Pheasant" },
{ value: "venison", label: "Venison" },
{ value: "rabbit", label: "Rabbit" },
{ value: "bison", label: "Bison" },
{ value: "octopus", label: "Octopus" },
{ value: "squid", label: "Squid" },
{ value: "clams", label: "Clams" },
{ value: "oysters", label: "Oysters" },
{ value: "scallops", label: "Scallops" },
{ value: "crab", label: "Crab" },
{ value: "anchovies", label: "Anchovies" },
{ value: "sardines", label: "Sardines" },
{ value: "mackerel", label: "Mackerel" },
{ value: "halibut", label: "Halibut" },
{ value: "cod", label: "Cod" },
{ value: "sea_bass", label: "Sea Bass" },
{ value: "trout", label: "Trout" },
{ value: "tilapia", label: "Tilapia" },
{ value: "swordfish", label: "Swordfish" },
{ value: "all_purpose_flour", label: "All Purpose Flour" },
{ value: "bread_flour", label: "Bread Flour" },
{ value: "cake_flour", label: "Cake Flour" },
{ value: "pastry_flour", label: "Pastry Flour" },
{ value: "whole_wheat_flour", label: "Whole Wheat Flour" },
{ value: "rye_flour", label: "Rye Flour" },
{ value: "spelt_flour", label: "Spelt Flour" },
{ value: "buckwheat_flour", label: "Buckwheat Flour" },
{ value: "rice_flour", label: "Rice Flour" },
{ value: "brown_rice_flour", label: "Brown Rice Flour" },
{ value: "chickpea_flour", label: "Chickpea Flour" },
{ value: "almond_flour", label: "Almond Flour" },
{ value: "coconut_flour", label: "Coconut Flour" },
{ value: "tapioca_flour", label: "Tapioca Flour" },
{ value: "cassava_flour", label: "Cassava Flour" },
{ value: "sorghum_flour", label: "Sorghum Flour" },
{ value: "millet_flour", label: "Millet Flour" },
{ value: "corn_flour", label: "Corn Flour" },
{ value: "masa_harina", label: "Masa Harina" },
{ value: "semolina_flour", label: "Semolina Flour" },
{ value: "barley_flour", label: "Barley Flour" },
{ value: "oat_flour", label: "Oat Flour" },
{ value: "amaranth_flour", label: "Amaranth Flour" },
{ value: "teff_flour", label: "Teff Flour" },
{ value: "quinoa_flour", label: "Quinoa Flour" },
{ value: "chestnut_flour", label: "Chestnut Flour" },
{ value: "potato_starch", label: "Potato Starch" },
{ value: "corn_starch", label: "Corn Starch" },
{ value: "arrowroot_starch", label: "Arrowroot Starch" },
{ value: "grapeseed_oil", label: "Grapeseed Oil" },
{ value: "avocado_oil", label: "Avocado Oil" },
{ value: "walnut_oil", label: "Walnut Oil" },
{ value: "sesame_oil", label: "Sesame Oil" },
{ value: "peanut_oil", label: "Peanut Oil" },
{ value: "coconut_oil", label: "Coconut Oil" },
{ value: "olive_oil", label: "Olive Oil" },
{ value: "flaxseed_oil", label: "Flaxseed Oil" },
{ value: "ghee", label: "Ghee" },
{ value: "lard", label: "Lard" },
{ value: "tallow", label: "Tallow" },
{ value: "guava", label: "Guava" },
{ value: "passion_fruit", label: "Passion Fruit" },
{ value: "dragon_fruit", label: "Dragon Fruit" },
{ value: "lychee", label: "Lychee" },
{ value: "rambutan", label: "Rambutan" },
{ value: "jackfruit", label: "Jackfruit" },
{ value: "durian", label: "Durian" },
{ value: "soursop", label: "Soursop" },
{ value: "persimmon", label: "Persimmon" },
{ value: "quince", label: "Quince" },
{ value: "kumquat", label: "Kumquat" },
{ value: "star_fruit", label: "Star Fruit" },
{ value: "urad_dal", label: "Urad Dal" },
{ value: "mung_dal", label: "Mung Dal" },
{ value: "masoor_dal", label: "Masoor Dal" },
{ value: "toor_dal", label: "Toor Dal" },
{ value: "chana_dal", label: "Chana Dal" },
{ value: "moong_dal", label: "Moong Dal" },
{ value: "black_gram", label: "Black Gram" },
{ value: "fava_beans", label: "Fava Beans" },
{ value: "lima_beans", label: "Lima Beans" },
{ value: "navy_beans", label: "Navy Beans" },
{ value: "kidney_beans", label: "Kidney Beans" },
{ value: "black_beans", label: "Black Beans" },
{ value: "pinto_beans", label: "Pinto Beans" },
{ value: "cannellini_beans", label: "Cannellini Beans" },
{ value: "chickpeas", label: "Chickpeas" },
{ value: "lentils", label: "Lentils" }
];
  