export const ingredientsList = [
    // Spices
    { value: "turmeric", label: "Turmeric" },
    { value: "cumin", label: "Cumin" },
    { value: "coriander", label: "Coriander" },
    { value: "mustard_seeds", label: "Mustard Seeds" },
    { value: "ginger", label: "Ginger" },
    { value: "garlic", label: "Garlic" },
    { value: "green_chilies", label: "Green Chilies" },
    { value: "onions", label: "Onions" },
    { value: "tomatoes", label: "Tomatoes" },
    { value: "curry_leaves", label: "Curry Leaves" },
    { value: "red_chili_powder", label: "Red Chili Powder" },
    { value: "garam_masala", label: "Garam Masala" },
    { value: "fenugreek_leaves", label: "Fenugreek Leaves" },
    { value: "cloves", label: "Cloves" },
    { value: "cardamom", label: "Cardamom" },
    { value: "cinnamon", label: "Cinnamon" },
    { value: "bay_leaves", label: "Bay Leaves" },
    { value: "black_pepper", label: "Black Pepper" },
    { value: "white_pepper", label: "White Pepper" },
    { value: "paprika", label: "Paprika" },
    { value: "nutmeg", label: "Nutmeg" },
    { value: "mace", label: "Mace" },
    { value: "star_anise", label: "Star Anise" },
    { value: "sumac", label: "Sumac" },
    { value: "saffron", label: "Saffron" },
    { value: "turmeric_root", label: "Turmeric Root" },
    { value: "asafoetida", label: "Asafoetida" },
    { value: "smoked_paprika", label: "Smoked Paprika" },
    { value: "cayenne_pepper", label: "Cayenne Pepper" },
    { value: "chili_flakes", label: "Chili Flakes" },
  
    // Herbs
    { value: "mint_leaves", label: "Mint Leaves" },
    { value: "basil_leaves", label: "Basil Leaves" },
    { value: "oregano", label: "Oregano" },
    { value: "thyme", label: "Thyme" },
    { value: "rosemary", label: "Rosemary" },
    { value: "parsley", label: "Parsley" },
    { value: "cilantro", label: "Cilantro" },
    { value: "dill", label: "Dill" },
    { value: "chives", label: "Chives" },
    { value: "tarragon", label: "Tarragon" },
    { value: "lemongrass", label: "Lemongrass" },
    { value: "bay_leaf", label: "Bay Leaf" },
    { value: "sage", label: "Sage" },
    { value: "fennel", label: "Fennel" },
  
    // Grains
    { value: "rice", label: "Rice" },
    { value: "quinoa", label: "Quinoa" },
    { value: "oats", label: "Oats" },
    { value: "barley", label: "Barley" },
    { value: "millet", label: "Millet" },
    { value: "couscous", label: "Couscous" },
    { value: "bulgur", label: "Bulgur" },
    { value: "farro", label: "Farro" },
    { value: "rye", label: "Rye" },
    { value: "spelt", label: "Spelt" },
    { value: "sorghum", label: "Sorghum" },
  
    // Vegetables
    { value: "potatoes", label: "Potatoes" },
    { value: "sweet_potatoes", label: "Sweet Potatoes" },
    { value: "carrots", label: "Carrots" },
    { value: "cauliflower", label: "Cauliflower" },
    { value: "broccoli", label: "Broccoli" },
    { value: "zucchini", label: "Zucchini" },
    { value: "eggplant", label: "Eggplant" },
    { value: "bell_peppers", label: "Bell Peppers" },
    { value: "spinach", label: "Spinach" },
    { value: "kale", label: "Kale" },
    { value: "mushrooms", label: "Mushrooms" },
    { value: "peas", label: "Peas" },
    { value: "green_beans", label: "Green Beans" },
    { value: "asparagus", label: "Asparagus" },
    { value: "artichoke", label: "Artichoke" },
    { value: "cabbage", label: "Cabbage" },
    { value: "brussels_sprouts", label: "Brussels Sprouts" },
    { value: "radishes", label: "Radishes" },
    { value: "cucumber", label: "Cucumber" },
    { value: "beets", label: "Beets" },
    { value: "lettuce", label: "Lettuce" },
    { value: "arugula", label: "Arugula" },
  
    // Fruits
    { value: "lemons", label: "Lemons" },
    { value: "limes", label: "Limes" },
    { value: "oranges", label: "Oranges" },
    { value: "apples", label: "Apples" },
    { value: "bananas", label: "Bananas" },
    { value: "grapes", label: "Grapes" },
    { value: "strawberries", label: "Strawberries" },
    { value: "blueberries", label: "Blueberries" },
    { value: "pineapple", label: "Pineapple" },
    { value: "mango", label: "Mango" },
    { value: "papaya", label: "Papaya" },
    { value: "watermelon", label: "Watermelon" },
    { value: "pears", label: "Pears" },
    { value: "plums", label: "Plums" },
    { value: "kiwi", label: "Kiwi" },
    { value: "pomegranate", label: "Pomegranate" },
  
    // Animal Products
    { value: "milk", label: "Milk" },
    { value: "eggs", label: "Eggs" },
    { value: "chicken", label: "Chicken" },
    { value: "beef", label: "Beef" },
    { value: "pork", label: "Pork" },
    { value: "lamb", label: "Lamb" },
    { value: "goat_meat", label: "Goat Meat" },
    { value: "salmon", label: "Salmon" },
    { value: "tuna", label: "Tuna" },
    { value: "lobster", label: "Lobster" },
    { value: "shrimp", label: "Shrimp" },
    { value: "mussels", label: "Mussels" },
    { value: "yogurt", label: "Yogurt" },
    { value: "butter", label: "Butter" },
    { value: "cheese", label: "Cheese" },
    { value: "cream", label: "Cream" },
    { value: "duck", label: "Duck" },
    { value: "turkey", label: "Turkey" },
    { value: "goose", label: "Goose" },
    { value: "sheep_milk", label: "Sheep Milk" },
    { value: "goat_cheese", label: "Goat Cheese" },
    { value: "duck_eggs", label: "Duck Eggs" },
    { value: "honey", label: "Honey" },
  
    // Nuts and Seeds
    { value: "peanuts", label: "Peanuts" },
    { value: "almonds", label: "Almonds" },
    { value: "walnuts", label: "Walnuts" },
    { value: "cashews", label: "Cashews" },
    { value: "pistachios", label: "Pistachios" },
    { value: "sunflower_seeds", label: "Sunflower Seeds" },
    { value: "chia_seeds", label: "Chia Seeds" },
    { value: "flax_seeds", label: "Flax Seeds" },
    { value: "pumpkin_seeds", label: "Pumpkin Seeds" },
    { value: "sesame_seeds", label: "Sesame Seeds" },
];
  